name: Release to PyPI

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"
    
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.7.20"
    
    - name: Install dependencies
      run: uv sync --all-extras --dev --locked
    
    - name: Run tests
      run: uv run pytest --tb=short -v
    
    - name: Build package
      run: uv build
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1